info:
  name : "集成Mybatis"

server:
  ##项目上下文，如果不设定，默认是 /
  servlet:
    context-path: /web

spring:
  ##默认使用配置
  profiles:
    active: dev

  ##动态模版配置
  thymeleaf:
    content-type:
      servlet: text/html
    encoding: UTF-8
    cache: false
    mode: HTML
    ##以下解決Error resolving template异常
    prefix: classpath:/templates/

  ##session存储类型
  session:
    store-type: redis
    ##设置session超时时间
    timeout: 2000

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lark.*.model  # 注意：对应实体类的路径

##pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

